# Publish GitHub workflow artifacts tutorial example
name: Download predictit market data

on:
  push:
    branches: [ main ]

jobs:

  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:


      - name: step 1 - Download xml file
        run: |
          wget https://www.predictit.org/api/marketdata/all -O data.xml

      - name: Step 2 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: data.xml
          path: data.xml
